version: '3.7'
services:
  postgres:
    container_name: madboks-db
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=madboks
      - POSTGRES_DB=madboks
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 4433:5432
