GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/countries
Accept: application/json
Content-type: application/json

###

GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/countries?filter[code]=DNK
Accept: application/json
Content-type: application/json

###

GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/countries/DNK
Accept: application/json
Content-type: application/json
