GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/products
Accept: application/json
Content-type: application/json

###

GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/products?filter[barcode]=0987654321
Accept: application/json
Content-type: application/json

###

GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/products/9b77bab5-723e-495a-9578-c2e4405cb3e1
Accept: application/json
Content-type: application/json
