GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/supermarkets
Accept: application/json
Content-type: application/json

###

GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/supermarkets?filter[name]=netto
Accept: application/json
Content-type: application/json

###

GET http://{{$dotenv API_HOST}}:{{$dotenv API_PORT}}/api/supermarkets/ef82a7b0-2ca0-4abc-88cf-f6b22d582773
Accept: application/json
Content-type: application/json
